### ISSUE TITLE
annotations: Crash on invalid move annotations

### ISSUE THREAD

**Issue by junghon3709** [hartwork/xiangqi-setup#113]
I have the following annofen file:

`v1 r1bakab1r/4c4/4c4/p1[n<a+1-2>]3p1p/9/3CC1P2/P1P1P3P/2N3N2/4A4/2BAK1B1R w - - 0 12`

This renders successfully. 

However, should I change the numbers in the arrows to:

`v1 r1bakab1r/4c4/4c4/p1[n<a+1-3>]3p1p/9/3CC1P2/P1P1P3P/2N3N2/4A4/2BAK1B1R w - - 0 12`, 

an error message pops up:

```
Traceback (most recent call last):
  File "`PATH`", line 8, in <module>
    sys.exit(main())
  File "`PATH`/__main__.py", line 260, in main
    run(options)
  File "`PATH`/__main__.py", line 60, in run
    atoms_to_put = list(iterate_annofen_tokens(content))
  File "/home/~/Documents/Projects/Xiangqi-Analyser/venv/lib/python3.8/site-packages/xiangqi_setup/file_formats/annofen.py", line 91, in iterate_annofen_tokens
    raise ValueError(f'Malformed annoFEN token: {character!r}')
ValueError: Malformed annoFEN token: '['
```

**Comment by hartwork** [comment]
Hi @junghon3709 nice to meet you!

I confirm the issue, here's what I did to reproduce based on your data on the terminal:

<details>
<summary>Click here to expand for details</summary>

```console
# cat issue-113.py 
from xiangqi_setup.file_formats.annofen import iterate_annofen_tokens, _escaped_annotation_names

with open('issue-113.annofen') as f:
   list(iterate_annofen_tokens(f.read()))

# cat issue-113.annofen 
v1 r1bakab1r/4c4/4c4/p1[n<a+1-3>]3p1p/9/3CC1P2/P1P1P3P/2N3N2/4A4/2BAK1B1R w - - 0 12

# python3.10 issue-113.py 
Traceback (most recent call last):
  File "/home/sping/__playground/xiangqi-setup/issue-113.py", line 4, in <module>
    list(iterate_annofen_tokens(f.read()))
  File "/home/sping/__playground/xiangqi-setup/xiangqi_setup/file_formats/annofen.py", line 92, in iterate_annofen_tokens
    raise ValueError(f'Malformed annoFEN token: {character!r}')
ValueError: Malformed annoFEN token: '['
```

</details>

What is happening here is that "+1-3" is not a valid move to the eyes of xiangqi-setup and the way the parser works makes it end up with this admittedly unhelpful-to-humans error. For each supported move there is one SVG file, e.g. see [this directory](https://github.com/hartwork/xiangqi-setup/tree/master/xiangqi_setup/themes/annotations/colors_alpha). If a move is legal to any of the pieces, it is supported, e.g. "a+1-2" is one out of eight for the knights/horses. The full list is this:

```
a+0+1 a+0-1 a+0+2 a+0-2 a+0+3 a+0-3 a+0+4 a+0-4 a+0+5 a+0-5 a+0+6 a+0-6 a+0+7 a+0-7 a+0+8 a+0-8 a+0+9 a+0-9 a+1+0 a-1+0 a+1+1 a+1-1 a-1+1 a-1-1 a+1+2 a+1-2 a-1+2 a-1-2 a+2+0 a-2+0 a+2+1 a+2-1 a-2+1 a-2-1 a+2+2 a+2-2 a-2+2 a-2-2 a+3+0 a-3+0 a+4+0 a-4+0 a+5+0 a-5+0 a+6+0 a-6+0 a+7+0 a-7+0 a+8+0 a-8+0
```

I have some hope that "+1-3" was in part a typo and that legal moves are enough for your use case? Then I would only need to improve the error message. I have some idea how to do that. What do you think, what was your intention when trying "+1-3"?

Best, Sebastian

**Comment by hartwork** [comment]
@junghon3709 what do you think?

**Comment by hartwork** [comment]
@junghon3709 what do you think?

**Comment by junghon3709** [comment]
I see now, I guess it makes sense to change the error message

**Comment by hartwork** [comment]
Version 2.2.0 with #123 merged released to GitHub and PyPI just now.

**Comment by junghon3709** [comment]
Thank you for the change!
