### ISSUE TITLE
Can you provide me example of how to use  --annotate-last-move  and   --moves COUNT  ?

### ISSUE THREAD

**Issue by somchai-x** [hartwork/xiangqi-setup#122]
WXF format arguments:
  --moves COUNT         how many moves to play (for a file with moves history),
                        e.g. "3" would play the first move of red, the first
                        move of black and the second move of red and then skip
                        any remaining moves, "all" would play all moves, "-1"
                        all moves but the last, "-2" all but the last two
                        (default: "0")
  --annotate-last-move  Add annotations "blank_move" and "piece_move" to the
                        source and target locations of the last move

**Comment by hartwork** [comment]
Hi @somchai-x I'm not sure I understand the question. Does this help?:

```console
# xiangqi-setup --annotate-last-move --moves 10 ./doc/demo-with-history-playok.wxf demo.svg
```

**Comment by somchai-x** [comment]
It works for me now. i just didn't update the version. But it is good to leave this useful comment here though
