### ISSUE TITLE
I do not understand annofen please help.

### ISSUE THREAD

**Issue by golf-x** [hartwork/xiangqi-setup#124]
v1 r[<bm><a+1-2>]bakabnr/9/1c[<pm>n]4c1/p1p1p1p1p/9/9/P1P1P1P1P/1C2[<pm>C]2[<bm><a-3+0>]1/9/RNBAKABNR

For example. How do we modify this to opposite cannon opening.

**Comment by hartwork** [comment]
@golf-x I think a key question here is whether you already understand FEN which annoFEN is based on. I recommend to interactively play with plain FEN at https://www.pychess.org/editor/xiangqi and then add annoFEN bits in in a text editor as a second step. Let me know how far you get.

**Comment by hartwork** [comment]
@golf-x PS: Did you see the docs at https://github.com/hartwork/xiangqi-setup/blob/master/doc/file_formats.md#annofen-file-format ?

**Comment by hartwork** [comment]
@golf-x PPS: There is also XAY documenation at https://github.com/hartwork/xiangqi-setup/blob/master/doc/file_formats.md#xay-file-format . Maybe XAY fits your needs better than annoFEN, just an idea.
