### ISSUE TITLE
I want to implement feature that support annotating last two moves. any advice ?

### ISSUE THREAD

**Issue by golf-x** [hartwork/xiangqi-setup#126]

**Comment by hartwork** [comment]
@golf-x I would like `--annotate-second-last-move` for a name. Using `git grep annotate.last.move` (with dot for regex) you can find the code backing the existing `--annotate-last-move`.

**Comment by golf-x** [comment]
![image](https://github.com/hartwork/xiangqi-setup/assets/2382992/e737efc5-c074-4563-af5f-c8493071a954)

I think I have updated the code correctly.
I want to test it by run on __main__.py and i got this error 

Exception has occurred: ImportError
attempted relative import with no known parent package
  File "/Users/golf/Documents/opensource/xiangqi-setup/xiangqi_setup/__main__.py", line 13, in <module>
    from .compose import cm_to_pixel, compose_svg
ImportError: attempted relative import with no known parent package

**Comment by hartwork** [comment]
@golf-x running `main.py` as is will not work. Here's two ways that do:

```console
cd "$(mktemp -d)"
git clone --depth 1 https://github.com/hartwork/xiangqi-setup
cd xiangqi-setup/
python3 -m venv venv
source venv/bin/activate
pip3 install -e '.[tests]'

xiangqi-setup --help             # method a, uses venv/bin/xiangqi-setup
python3 -m xiangqi_setup --help  # method b, uses __main__.py
```

**Comment by golf-x** [comment]
It works now.
Is it a good idea to add these code it Makefile.
Also, should we add venv in gitignore ?

**Comment by golf-x** [comment]
![Uploading image.png…]()

The menu works fine now.
I am going to test it manually and maybe add documentation or tests.
going to study more on codebase.

**Comment by hartwork** [comment]
> Is it a good idea to add these code it Makefile.

@golf-x maybe we should drop `Makefile` altogether. It feels a bit out of place by now.

> Also, should we add venv in gitignore ?

@golf-x no objections.

**Comment by hartwork** [comment]
> > Is it a good idea to add these code it Makefile.
> 
> @golf-x maybe we should drop `Makefile` altogether. It feels a bit out of place by now.

Now dropped in #132.

> 
> > Also, should we add venv in gitignore ?
> 
> @golf-x no objections.

Added in #131.

**Comment by golf-x** [comment]
Sorry, At the time I have been busy with my life circumstances.
I am OK if this issue be closed or if anyone else would have interested in implementing this.

**Comment by hartwork** [comment]
@golf-x thanks for the update, I'll close for now as suggested.
